name: pages

on: pull_request


jobs:
  update_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Clone ms3
        uses: actions/checkout@v2
        with:
          repository: johentsch/ms3
          ref: workflow
          path: ./ms3
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ./ms3
      - name: Clone corpusstats
        uses: actions/checkout@v2
        with:
          repository: DCMLab/corpus_statistics_generator
          path: ./corpusstats
          token: ${{ secrets.PAC }}
      - name: Install corpusstats
        run: python -m pip install -e ./corpusstats
      - name: Install dependencies
        run: |
          python -m pip install plotly
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display changed files
        run: cat ${HOME}/files_modified.json
      - name: Copy existing page
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: gh-pages
          path: ./public
      - name: Generate GitHub pages
        working-directory: ./main
        run: |
          python .github/workflows/update_pages.py -f ${HOME}/files_modified.json -o ../public
      - name: Display generated files
        working-directory: ./public
        run: ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
